# Generated by Django 2.2.4 on 2019-12-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chatroom_name', models.CharField(max_length=50)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
