# Generated by Django 2.2.7 on 2019-12-20 07:52

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_id', models.IntegerField()),
                ('comment_author_id', models.CharField(max_length=64)),
                ('comment_publish_date', models.DateTimeField(auto_now_add=True)),
                ('comment_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDiscussions',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('discussion_author_id', models.CharField(max_length=64)),
                ('discussion_publish_date', models.DateTimeField(auto_now_add=True)),
                ('discussion_title', models.CharField(max_length=32)),
                ('discussion_description', models.TextField(max_length=500)),
                ('discussion_maximum_comments', models.IntegerField(default=100)),
                ('discussion_type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24)),
                ('user_description', models.TextField(max_length=256, null=True)),
                ('user_following', models.TextField(null=True)),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to=community.models.get_image_path)),
                ('user_date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
