# Generated by Django 2.2.4 on 2019-12-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversations',
        ),
    ]
