# Generated by Django 2.2.4 on 2019-12-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_conversations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationMessages',
        ),
        migrations.DeleteModel(
            name='Conversations',
        ),
    ]
