# Generated by Django 2.2.7 on 2019-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191221_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user_following',
            field=models.TextField(default='{"following": [], "discussions": []}'),
        ),
    ]
