# Generated by Django 2.2.7 on 2019-12-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191221_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='user_threads',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_following',
            field=models.TextField(default='[]'),
        ),
    ]
