# Generated by Django 2.2.4 on 2019-12-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20191224_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessages',
            fields=[
                ('conversation_id', models.IntegerField()),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ids', models.TextField(default='')),
                ('conversation_title', models.CharField(default='', max_length=32)),
                ('conversation_history', models.TextField(default='')),
                ('admin_id', models.CharField(max_length=24)),
            ],
        ),
    ]
