# Generated by Django 2.2.4 on 2020-01-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_conversationmessages_conversations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessages',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_user_id', models.IntegerField()),
                ('notification_url', models.CharField(max_length=256)),
                ('notification_text', models.CharField(max_length=512)),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
