# Generated by Django 2.2.7 on 2019-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20191221_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user_following',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_threads',
            field=models.TextField(default=''),
        ),
    ]
