# Generated by Django 2.2.7 on 2019-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191221_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
