# Generated by Django 2.2.7 on 2019-12-21 10:27

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20191221_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user_profile_image',
            field=models.ImageField(default='profile/profile.jfif', upload_to=community.models.get_image_path),
        ),
    ]
