# Generated by Django 2.2.9 on 2019-12-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20191221_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ids', models.TextField(default='')),
                ('conversation_title', models.CharField(default='', max_length=32)),
                ('conversation_history', models.TextField(default='')),
                ('admin_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='communitydiscussions',
            name='discussion_tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='user_saved_threads',
            field=models.TextField(default=''),
        ),
    ]
