# Generated by Django 2.2.4 on 2019-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20191222_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessages',
            fields=[
                ('conversation_id', models.IntegerField()),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
